theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 30
warning = 20.0
alert = 10.0

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
interval = 10
collapsed = false
format = "{min}° min, {max}° max"

[[block]]
block = "net"
device = "enp0s31f6"
interval = 5
ip = true

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
marquee = false
max_width = 30

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %b %d %R"
